[package]
name = "utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
rayon = "1.8.0"
clap = { version = "4.4.8", features = ["derive"] }
clap-num = "1.0.2"
